# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import user.proto_generated.dispatcher_pb2 as dispatcher__pb2


class DispatcherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.request_verification = channel.unary_unary(
            "/zk_kyc.Dispatcher/request_verification",
            request_serializer=dispatcher__pb2.UserRequest.SerializeToString,
            response_deserializer=dispatcher__pb2.UserResponse.FromString,
        )


class DispatcherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def request_verification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DispatcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "request_verification": grpc.unary_unary_rpc_method_handler(
            servicer.request_verification,
            request_deserializer=dispatcher__pb2.UserRequest.FromString,
            response_serializer=dispatcher__pb2.UserResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "zk_kyc.Dispatcher", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Dispatcher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def request_verification(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/zk_kyc.Dispatcher/request_verification",
            dispatcher__pb2.UserRequest.SerializeToString,
            dispatcher__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
