# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import verifier_server.proto_generated.verifier_pb2 as verifier__pb2


class VerifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.verify_proof = channel.unary_unary(
            "/zk_kyc.Verifier/verify_proof",
            request_serializer=verifier__pb2.VerificationRequest.SerializeToString,
            response_deserializer=verifier__pb2.VerificationResponse.FromString,
        )


class VerifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def verify_proof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_VerifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "verify_proof": grpc.unary_unary_rpc_method_handler(
            servicer.verify_proof,
            request_deserializer=verifier__pb2.VerificationRequest.FromString,
            response_serializer=verifier__pb2.VerificationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "zk_kyc.Verifier", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Verifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def verify_proof(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/zk_kyc.Verifier/verify_proof",
            verifier__pb2.VerificationRequest.SerializeToString,
            verifier__pb2.VerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
