[package]
name = "zkkyc_c_bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
zkkyc_lib = {path = "../zkkyc_lib"}

[build-dependencies]
cbindgen = "0.24.3"
