services:
  vdr-server:
    image: clickhouse/clickhouse-server
    container_name: vdr-clickhouse-server
    ports:
      - "18123:8123"
      - "19000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --query 'SELECT 1'" ]
      interval: 10s
      timeout: 10s
      retries: 3

  vdr-filler:
    image: python:3.10.8
    container_name: vdr-filler
    depends_on:
      vdr-server:
        condition: service_healthy
    network_mode: "host"
    volumes:
      - type: bind
        source: vdr/fill_db.py
        target: /fill_db.py
      - type: bind
        source: vdr/db_test_data.csv
        target: /db_test_data.csv
      - type: bind
        source: vdr/requirements.txt
        target: /requirements.txt
    entrypoint: /bin/bash
    command:
      [
        "-lc",
        "pip install -r requirements.txt && python fill_db.py"
      ]

  prover-server:
    image: zk-kyc/prover-server
    build:
      context: .
      dockerfile: prover_server/Dockerfile
      network: host
    container_name: prover-server
    network_mode: "host"
    volumes:
      - type: bind
        source: config/prover_server.toml
        target: /config/prover_server.toml
      - type: bind
        source: lib/libzkkyc_c_bindings.so
        target: /lib/libzkkyc_c_bindings.so
    command: [ "--config", "config/prover_server.toml" ]

  verifier-server:
    image: zk-kyc/verifier-server
    build:
      context: .
      dockerfile: verifier_server/Dockerfile
      network: host
    container_name: verifier-server
    network_mode: "host"
    volumes:
      - type: bind
        source: config/verifier_server.toml
        target: /config/verifier_server.toml
      - type: bind
        source: lib/libzkkyc_c_bindings.so
        target: /lib/libzkkyc_c_bindings.so
    command: [ "--config", "config/verifier_server.toml" ]

  dispatcher-server:
    image: zk-kyc/dispatcher-server
    build:
      context: .
      dockerfile: dispatcher_server/Dockerfile
      network: host
    container_name: dispatcher-server
    network_mode: "host"
    volumes:
      - type: bind
        source: config/dispatcher_server.toml
        target: /config/dispatcher_server.toml
      - type: bind
        source: config/kyc_params.json
        target: /config/kyc_params.json
      - type: bind
        source: config/provers_list.json
        target: /config/provers_list.json
    command: [ "--config", "config/dispatcher_server.toml" ]

  user-client:
    image: zk-kyc/user
    build:
      context: .
      dockerfile: user/Dockerfile
      network: host
    container_name: user
    depends_on:
      - dispatcher-server
    network_mode: "host"
    volumes:
      - type: bind
        source: config/user.toml
        target: /config/user.toml
    command: [ "--config", "config/user.toml" ]
