# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispatcher.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x64ispatcher.proto\x12\x06zk_kyc".\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0e\n\x06vdr_id\x18\x02 \x01(\x04"K\n\x0cUserResponse\x12\x12\n\nkyc_result\x18\x01 \x01(\x08\x12\x13\n\x0bstatus_code\x18\x02 \x01(\r\x12\x12\n\nstatus_msg\x18\x03 \x01(\t2Q\n\nDispatcher\x12\x43\n\x14request_verification\x12\x13.zk_kyc.UserRequest\x1a\x14.zk_kyc.UserResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "dispatcher_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _USERREQUEST._serialized_start = 28
    _USERREQUEST._serialized_end = 74
    _USERRESPONSE._serialized_start = 76
    _USERRESPONSE._serialized_end = 151
    _DISPATCHER._serialized_start = 153
    _DISPATCHER._serialized_end = 234
# @@protoc_insertion_point(module_scope)
