# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import dispatcher_server.proto_generated.prover_pb2 as prover__pb2
import grpc


class ProverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_proof = channel.unary_unary(
            "/zk_kyc.Prover/get_proof",
            request_serializer=prover__pb2.ProofRequest.SerializeToString,
            response_deserializer=prover__pb2.ProofResponse.FromString,
        )


class ProverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_proof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ProverServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "get_proof": grpc.unary_unary_rpc_method_handler(
            servicer.get_proof,
            request_deserializer=prover__pb2.ProofRequest.FromString,
            response_serializer=prover__pb2.ProofResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "zk_kyc.Prover", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Prover(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_proof(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/zk_kyc.Prover/get_proof",
            prover__pb2.ProofRequest.SerializeToString,
            prover__pb2.ProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
